version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask-todo
    overwrite: true

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 180
      runas: root
