version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Testing the build
      - docker run --rm $IMAGE_REPO_NAME:$IMAGE_TAG sh -c "pip install -r test-requirements.txt && export FLASK_APP=todolist.py && flask test"
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files: 
      - 'codeDeploy/**/*'
      - 'docker-compose.yml'
      - 'appspec.yml'
      - '.env'
  discard-paths: yes