version: '2'
services:
  todolist:
    container_name: todolist
    image: arbabkhalil/test_jenkins
    # restart: always
    env_file: .env
    command: sh -c "flask db upgrade && gunicorn todolist:app -w 2 -b :8000"

    ports:
      - "8000:8000"

  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: